AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyCustomResource:
    Type: "Custom::WeatherAppDeployment"
    Properties:
      ServiceToken: YOUR_LAMBDA_ARN
      Region: !Ref AWS::Region
      AccountId: !Ref AWS::AccountId
      APICodeUrl: https://github.com/blytheaw/vf-coding-assignment/releases/download/1/weather-api-function.zip
      SPACodeUrl: https://github.com/blytheaw/vf-coding-assignment/releases/download/1/weather-app.zip
      OpenWeatherApiKey: YOUR_OPENWEATHER_APIKEY
Outputs:
  S3WebsiteUrl:
    Description: S3 Static Website URL
    Value: !GetAtt MyCustomResource.s3WebsiteUrl
