name: Weather App Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.run_number }}
          release_name: ${{ github.run_number }}

      - name: Build Weather SPA
        run: |
          npm install
          npm run build:prod
          cd dist/weather-app
          zip -r ../weather-app.zip .
        working-directory: weather-app

      - name: Upload Weather SPA Code
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./weather-app/dist/weather-app.zip
          asset_name: weather-app.zip
          asset_content_type: application/zip

      - name: Build Weather API
        run: |
          npm install
          npm run sls:package
        working-directory: weather-api

      - name: Upload Weather API Code
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./weather-api/.serverless/weather-api.zip
          asset_name: weather-api-function.zip
          asset_content_type: application/zip
